- src/DicomMetaDictionary.js
It was included a new rule to throw an error when there is at least one undefined value under the natural values if it is an array
When this situation occurs, the `denaturalizeValue` method fails ungraceful:
`Uncaught TypeError: Cannot read property 'constructor' of undefined`
This PR is related to issue https://github.com/dcmjs-org/dcmjs/issues/42
> adding rule to throw an error when naturalValue is an array with undefined values

- src/adapters/DICOMMicroscopyViewer/MeasurementReport.js
- src/adapters/DICOMMicroscopyViewer/Polyline.js
replacing scoord to scoord3d and adding toolType in Polyline
Since all coords are now in scoord3d format, the ROI should be able to get scoord3d elements
> replacing scoord to scoord3d and adding toolType in Polyline

- src/datasetToBlob.js
- src/index.js
node.js doesn't support the Blob type natively. The simple solution (suggested by @JamesAPetts) was to refactor **datasetToBlob()** into smaller chunks, **datasetToDict()** and **datasetToBuffer()**. This lets me read and write DICOM pretty easily:
`
const dicomData = DicomMessage.readFile(fs.readFileSync(source).buffer, {ignoreErrors: false});
const dataset = DicomMetaDictionary.naturalizeDataset(dicomData.dict);
dataset._meta = DicomMetaDictionary.namifyDataset(dicomData.meta);
fs.appendFileSync(destination, datasetToBuffer(dataset));
`
I've confirmed that **datasetToBlob()** functions the same as it did previously, at least in the context of an Electron application.
> Divided datasetToBlob() into dict, buffer, & blob

- src/utilities/Message.js
- src/utilities/index.js
I moved the message from dicomweb-client as we discussed with Steve. However, multipartdecode was having problems with separating a multipart file I downloaded from dcm4chee (Steve's instance). It was partitioning ok but the dcmjs readFile wasn't finding the DICM it was looking for on the files after the first and rejecting the file saying it is not a dicom. I fixed it by finding 2 consequent crlfs after the boundary. The standard says that if the "preamble" area is not used, the entity headers must be followed by TWO CRLFs (from https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html). I'm not sure it it will cover everything, any ideas @swederik
> Reorganization for server

- examples/createSegmentation/index.html
- examples/createSegmentationMultiframe/index.html
- examples/displaySegmentation/index.html
- examples/index.html
- src/adapters/Cornerstone/Segmentation.js
- src/derivations/Segmentation.js
- Correctly populate `SourceImageSequence` groups of the `PerFrameFunctionalGroups` for segmentations that reference both single framed and multi-framed image data.
- Updated `createSegmentation` example to allow drawing of multiple segments. Improved the Cornerstone adapter to support this.
- Support metadata providers that return `rowCosines`/`columnCosines` in either array or `{x, y, z}` format ala OHIF.
> Multi segmentation round2

- package.json
- src/adapters/Cornerstone/Segmentation.js
Correctly find `cornerstoneWADOImageLoader` `imageId`s given `SOPInstanceUID` and `FrameNumber` for Segmentation cornerstone import.
This really should have been in my last PR. Even though my last PR only patched incomplete functionality, I'm now developing on a local NPM lib and will PR only more complete patches.
> Load Segmentation onto correct cornerstone imageIds for multiframe images.

- package.json
- src/adapters/Cornerstone/Segmentation.js
Allow options to be parsed to adapters.Cornerstone.Segmentation.generateSegmentation, so one can change the SeriesDescription, etc, of the generated Segmentation.
> Added options field to cornerstone Segmentation generation.

- src/adapters/DICOMMicroscopyViewer/Circle.js
- src/adapters/DICOMMicroscopyViewer/MeasurementReport.js
- src/adapters/DICOMMicroscopyViewer/Point.js
- src/adapters/DICOMMicroscopyViewer/Polygon.js
- src/adapters/DICOMMicroscopyViewer/Polyline.js
- src/adapters/DICOMMicroscopyViewer/index.js
- src/utilities/TID300/Circle.js
- src/utilities/TID300/Point.js
- src/utilities/TID300/Polygon.js
- src/utilities/TID300/Polyline.js
Creating adapters for MicroscopyViewer.
There is a necessity to generate a report based on the tool the user selected [Box, Line, etc] and then retrieve it back.
An example page was built to generate the report (write): https://github.com/dcmjs-org/dcmjs-examples/blob/microscopy-example/microscopy/generateReport/index.html
and another one to read the report genereated
or read a default report just for test case
> Generate/Load SR for microscopy viewer tools

- examples/createSegmentation/index.html
- package-lock.json
- package.json
- src/derivations/Segmentation.js
- src/normalizers.js
`ReferencedSOPClass` -> `ReferencedSOPClassUID` in a few places. Previously some derived exports had an erroneous field when exported.
> Referenced instance sequence fix

- src/BufferStream.js
**WHAT**
in checkSize of BufferStream.js, resize buffer appropriate size instead of just increase buffer size double.
**WHY**
If step size is bigger than buffer length, just increasing buffer size double produce offset error as follows.
```
Error: Offset is outside the bounds of the DataView
```
> Fix Dataview offset out of bounds bug

- package-lock.json
- package.json
- src/DicomMetaDictionary.js
- src/datasetToBlob.js
- src/index.js
- src/sr/coding.js
- src/sr/contentItems.js
- src/sr/documents.js
- src/sr/index.js
- src/sr/templates.js
- src/sr/valueTypes.js
This PR implements structured reporting analogous to the *pydicom* implementation by exposing an intuitive, object-oriented interface for creation of SR documents based on template TID 1500 Measurement Report.
Commit 678543c introduces the `sr` sub-package with the intent to replace `adapters`. The adapter approach has several shortcomings in my opinion. First, the implementation is incomplete and generated SR documents are not standard compliant (several required attributes are missing, etc.). Second, the library would ideally not be aware of other tools, which in turn depend on the library.
The constructors of classes for DICOM templates, content items and value types defined in `sr.templates`, `sr.contentItems` and `sr.valueTypes`, respectively, perform many checks on the `options` …
> Implementation of Structured Reporting

- src/DicomMessage.js
Issue: 
- Now that some of the values are numbers, val.split not always exists.
Proposed fix: 
- test if val is a string first, if not, we just add the value as it will be a number.
> Fix number val

- src/DicomMetaDictionary.js
WADO-RS headers often come back with type 2 DICOM tags that have no Value entry. This currently breaks the naturalizer. This fixes that by skipping over these entries.
I'd argue that its more "natural" to not add empty type 2 tags to the "naturalized" (i.e. human readable datasets), but we can add them in later if removing them is deemed unnatural.
> Fix parsing of WADO-RS headers.

- src/DicomMetaDictionary.js
- test/test_data.js
The static methods `cleanDataset`, `namifyDataset`, and `naturalizeDataset` in DicomMetaDictionary have the side effect of changing the original dataset for sequence tags. `cleanDataset` also modified original values when converting nulls to empty strings.
I added Object.assign and array.map so that the output datasets get their own copies of non-primitives, and the input is safely unchanged.
I encountered this problem when trying to call `DicomMetaDictionary.naturalizeDataset` more than once on the same dataset. It would throw a `TypeError: Cannot read property 'length' of undefined` on the second pass.
Edit: Looks like `naturalizeDataset` was refactored while I was sleeping 😁, so this change now only applies to the clean and namify methods.
> Avoid mutation in static DicomMetaDictionary methods

- src/ValueRepresentation.js
Fix for #96 . Convert array of Numbers to array of Strings before writing.
> Convert Number to String before writing Decimal and Integer Strings.

- src/DicomMetaDictionary.js
Tags with falsy values are removed when a naturalized dataset object is converted into a blob. For example, tags with value 0 should be retained.
> Fix tags with value 0 lost when saving

- src/adapters/Cornerstone/Segmentation_4X.js
In some cases, each frame is encoded for each segment even if it's empty. Checking each frame for occupancy would be slow, which is why we do the segmentsOnLabelmap2D.
Solution:
Check which frame is occupied by a single positive bit, and only add these ones to the list.
Related Issues:
- https://github.com/OHIF/Viewers/pull/1643
> Segmentation Fix: Ignore empty seg frames

- src/DicomMetaDictionary.js
After the update done by PR [116](https://github.com/dcmjs-org/dcmjs/pull/116) to fix the issue #115 DCMJS can't parse null values which he sets himself when naturalizing the dataset value at [DicomMetaDictionary#L107](https://github.com/dcmjs-org/dcmjs/blob/master/src/DicomMetaDictionary.js#L107) causing an error to be thrown at [DicomMetaDictionary#L160](https://github.com/JoosaT/dcmjs/blob/9baed8983554d1583cc802c5d6d3dad0e02426bb/src/DicomMetaDictionary.js#L160).
This PR only adds an extra validation to the dataValue, skipping the parsing if the value is either `undefined` or `null`
> Adding null verification when denaturalizing the dataset values

- README.md
- src/DicomMetaDictionary.js
When denaturalizing tags we are not considering type 2 tags with null values and removing then from the dataset, which is wrong. This PR will consider null values as correct and jump all parsing and directly return the tag value as null.
> Bug: Considering type 2 tags when denaturalizing

- src/ValueRepresentation.js
Skipping length check for type 2 string tags when they are null.
> Fix: skipping length check for null string values

- src/adapters/Cornerstone/EllipticalRoi.js
- src/adapters/Cornerstone/Freehand.js
- src/adapters/Cornerstone/index.js
This PR exposes the cornerstone `ArrowAnnotate` adapter and removes the implcit cornerstoneMath dependency from the ellipse adapter.
> fix: Expose arrow annotate

- examples/cornerstoneDICOMSR/index.html
- src/adapters/Cornerstone/Bidirectional.js
- src/adapters/Cornerstone/EllipticalRoi.js
Sometime between CST `4.3` and `4.16.1` some fields where added to the bidirectional tool schema which are actually breaking schema changes.
CST itself has no IO tests at the moment, so it appears this was missed. This fix fixes the import from SR using  `dcmjs`.
> Cst bidirectional schema

- examples/cornerstoneDICOMSR/index.html
- src/adapters/Cornerstone/ArrowAnnotate.js
- src/adapters/Cornerstone/Bidirectional.js
- src/adapters/Cornerstone/EllipticalRoi.js
- src/adapters/Cornerstone/Length.js
- src/utilities/TID300/TID300Measurement.js
If a cornerstone measurement has `findings` or `findingSites`, encode these in the SR. If an SR has `Finding`s or `Finding Site`s, attach these to the cornerstone measurements when the cornerstone adapter is used.
There are also generic `Finding Site` groups added to the TID300 class, that allow you to pass in a `findingSites` array of the form:
```
[
{
CodeValue: "SAMPLE FINDING SITE",
CodingSchemeDesignator: "99dcmjs",
CodeMeaning: "Sample Finding Site"
},
// More entries
]
```
Which will build appropriate `Finding Site` content items, similar to the already existing functionaly for `Findings`.
> Cornerstone findings

- src/DicomMessage.js
- src/adapters/Cornerstone/ArrowAnnotate.js
Fixes a typo that broke import of arrow annotations.
> fix: 🐛 Fix arrow annotate cornerstone parsing

- src/adapters/DICOMMicroscopyViewer/Circle.js
- src/adapters/DICOMMicroscopyViewer/Ellipse.js
- src/adapters/DICOMMicroscopyViewer/MeasurementReport.js
- src/adapters/DICOMMicroscopyViewer/Point.js
- src/adapters/DICOMMicroscopyViewer/Polygon.js
- src/adapters/DICOMMicroscopyViewer/Polyline.js
- src/adapters/DICOMMicroscopyViewer/index.js
- src/adapters/helpers.js
This PR fixes the microscopy `MeasurementReport.generateToolState()` function so that it correctly identifies and extracts all measurement groups.
The implementation on master currently:
- Has an incorrect `graphicTypeEquals` function considering the data passed to it, meaning the data returned is empty.
-  Has `getMeasurementData`  methods for the microscopy SCOORD3D adapaters which check for `GraphicData` to be under a `ContentSequence`, whilst its actually at the root of the `contentItem` passed to the function.
- Only looks for one measurement group, instead of processing them all.
This PR fixes these issues.
I tested this from within another app, but I fixed it such that the pattern presented in `dcmjs-examples` works, e.g.:
```js
function getROIFromToolState(toolState) {
const tools …
```
> fix: 🐛 Fix Microscopy import

- examples/createSegmentation/index.html
- src/adapters/Cornerstone/Segmentation_4X.js
- src/derivations/Segmentation.js
DICOM Segmentation objects can have their referenced data encoded in multiple ways. The cornerstone adapter now parses a greater selection, tested on a lot of TCIA cases.
> fix: 🐛 Harden Segmentation import for different possible SEGs

- src/DicomDict.js
- src/DicomMessage.js
- src/Tag.js
- src/ValueRepresentation.js
- test/test_data.js
- Use offset table for reading fragments if present, otherwise, loop until end of stream/sequence
Issue I was seeing was with a multiframe US instance with no offset table (length == 0), and dcmjs would then assume there were no frames. This changes that behavior to go ahead and try to parse the pixel data sequence, which is what dicomParser does.
- Add option to not fragment encapsulated pixel data (use fragments equal to frame size)
Discussion with others on the open source imaging zoom call seemed to suggest that pixel data fragmentation is partly an artifact of older machines that could not buffer entire large instances in memory. This adds an option not to fragment when writing encapsulated pixel data, which in my brief tests seems to be a lot faster for large cine instances.
> Fix multiframe read/write

- test/test_data.js
- test/tests.js
This lets you easily run just a subset of the tests, using a simple pattern:
`npm run test [pattern]` will only run tests that contain `[pattern]` in the name, not case sensitive. Helpful for development.
> Add pattern matching for running one test from command line

- src/normalizers.js
If datasets aren't already in order, the datasets where getting sorted then given the unsorted IPP. This if now fixed.
> fix: 🐛 When converting to multiframe, fix IPP issues

- src/BufferStream.js
- src/ValueRepresentation.js
Hi, team,
This is to fix the issues #159: https://github.com/dcmjs-org/dcmjs/issues/159
It takes a lot of time (or the app crashes with heap out of bound) when writing bytes for an encapsulated multiframe images.
This is caused by too many BufferStream's "concat" method call to concatenate fragmented binary stream when dealing with a multiframe image, resulting in too many times of ArrayBuffer creation. This leads to O(n^2) on the memory (& time) complexity of writing DICOM data.
I tested with a sample image that has encapsulated pixel data and 120 frames:
https://oculusstoragestaging.blob.core.windows.net/error-testing/IM-0001-0010.dcm?sv=2019-12-12&st=2021-01-11T14%3A29%3A14Z&se=2021-02-11T14%3A29%3A00Z&sr=b&sp=r&sig=94kfZANKkjjd1q4GsgMaDkPG8vSEoHKTwQk6vG3A6s0%3D
Before this patch, it …
> fix improves the speed of writing bytes for an encapsulated multiframe image (#159)

- src/adapters/Cornerstone/Segmentation_4X.js
OHIF Issue: #2252
When ReferencedSegmentNumber IS available in the shared FG, and it does not need to be replicated in the per-frame FG. 
This code uses the shared value if no per-frame is available.
> fix(seg): Use ReferencedSegmentNumber in shared FG

- src/adapters/Cornerstone/Segmentation_4X.js
I just changed require to the import statement.
I didn't upgrade rollup this time. 
Rollup seems to have a breaking change in a newer version, but I'm not familiar with the library.
> fix "require is not defined" issue in the browser #170

- generate-dictionary.js
- package-lock.json
- package.json
- src/dictionary.js
Our de-identification service is encountering tags that are not defined in the dictionary. I did an audit and found around 800 tags that are missing from the dictionary module. I took the [approach of PyDICOM](https://github.com/pydicom/pydicom/blob/8112bb69bfc0423c3a08cb89e7960defbe7237bf/source/generate_dict/generate_dicom_dict.py) to generate the missing tags with a Node.js script that parses the DICOM standard documentation XML and adds new tags to the dictionary module without clobbering the existing format and ordering. GitHub won't render the diff but it looks pretty clean in VSCode + GitLens.
> Update dictionary from the DICOM standard documentation

- src/adapters/Cornerstone/Segmentation_4X.js
Fixes the issue: https://github.com/dcmjs-org/dcmjs/pull/166
(tested using segment example)
Updates getSegmentIndex method with new fallback list:
- PerFrameFunctionalGroups
- PerFrameFunctionalGroupsSequence
- SharedFunctionalGroupsSequence
> IDC-2252: Update getsegmentindex to use frame index

- src/DicomMessage.js
- test/test_data.js
- test/test_untilTag.js
This pull request adds `untilTag` as a parameter for the `read`, `readTag`, and `readFile` functions so that the user can choose to ignore the rest of a DICOM file. A boolean flag `includeUntilTagValue` has also been added that returns the values of the given `untilTag` before ignoring the rest of the DICOM file.
PR has successfully run `npm test` and `npm run build`.
Related PR/Issues:
#134
#149 
#181
> Added untilTag and includeUntilTagValue as an option for DICOM file reading

- src/adapters/Cornerstone/MeasurementReport.js
Add a new hook to allow other applications to define their own matching logic to map a measurement group to a Cornerstone tool class instead of purely relying on tracking identifiers.
- Opened PR (waiting for this merge): https://github.com/ImagingDataCommons/Viewers/pull/81
- Necessary for ticket (CCC annotations to Cornerstone): https://github.com/OHIF/Viewers/issues/1215
which allows the mapping from Crowds Cure Cancer uni and bidirectional annotations to Length and Bidirectional Cornerstone tool types.
- Datasets for uni directional: https://wiki.cancerimagingarchive.net/display/DOI/Crowds+Cure+Cancer%3A+Data+collected+at+the+RSNA+2017+annual+meeting
- Datasets for bi direictional: https://wiki.cancerimagingarchive.net/display/DOI/Crowds+Cure+Cancer%3A+Data+collected+at+the+RSNA+2018+a …
> IDC-1215: Add hook to allow custom mapping of measurement group to Cornerstone tool class

- src/adapters/Cornerstone/Segmentation_4X.js
This PR proposes to fix a problem that causes the omission of the first pixel of every segment on frame. 
You could generate a segmentation with a square region,  when this segmentation is imported you should see a missing pixel in the top-left corner.
> Fix: First pixel of a segment was omitted.

- src/DicomMetaDictionary.js
- test/test_data.js
Single item sequences like Shared Functional Groups are very convenient to access as singleton items, but others like the per-item functional groups are typically accessed as a arrays, even when they have only a single item in them.  This change preserves the "arrayness" of the items even of single-item values, but also preserves the singleton items, so that it is possible to access either:
metadata.SharedFunctionalGroupsSequence[0]
and get the same value as:
metadata.SharedFunctionalGroupsSequence
> Make single item arrays into both array items the item value itself

- src/DicomMessage.js
- src/Tag.js
Currently, when the transfer syntax of a DICOM is Implicit VR Endian (1.2.840.10008.1.2), the VR of the private creator tag is set to "UN"
According to the DICOM spec, this should be set to "LO". https://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_7.8.1
> Invalid VR of the private creator tag of the "Implicit VR Endian" typed DICOM file (#241)

- src/adapters/Cornerstone/Segmentation_4X.js
Fix regression https://github.com/dcmjs-org/dcmjs/issues/255 from https://github.com/dcmjs-org/dcmjs/pull/253.
After talking with David and in the light of the regression, we decided to first use the ReferencedSOPInstanceUID and then other logics (in the case ReferencedSOPInstanceUID is missing)
> Fix retrieve seg referenced instance

- README.md
Account for bad semantic release commit in https://github.com/dcmjs-org/dcmjs/pull/256
> fix: update readme to trigger release

- package.json
- src/adapters/Cornerstone3D/PlanarFreehandROI.js
Instead of pushing the first point again to encode a closed contour, we were pushing the last point again.
> Fix erroneous point in dcmjs

- src/adapters/Cornerstone3D/ArrowAnnotate.js
- src/adapters/Cornerstone3D/EllipticalROI.js
- src/adapters/Cornerstone3D/MeasurementReport.js
- src/adapters/Cornerstone3D/index.js
- Expose constants for Cornerstone3D 
- Fix tool state generation for Arrow annotate
- Fix the Backward compatibility with legacy cornerstone for arrow
> fix: ArrowAnnotateTool adapter in Cornerstone3D parsing label

- src/BufferStream.js
- src/ValueRepresentation.js
This PR changes the ReadBufferStream to not allocate new memory ArrayBuffers when calling `.more` The idea being that ReadBufferStreams can be treated as a "View" on top of some underlying ArrayBuffer sitting in memory.
- It doesn't really change the speed performance.
- I haven't done any memory profiling.
Thoughts? :+1: :-1:
> Zero Copy ArrayBuffer

- src/ValueRepresentation.js
- test/data.test.js
This is needed when doing C-FIND with dcmjs-dimse, where "" means 'match everything', not zero.
> Convert empty DecimalString and NumberString to null instead of zero

- src/BufferStream.js
I was able to speed up writing segmentations for large series (>1000 images) by a factor of 10 in Firefox with this fix
The problem was too many buffer copies when the buffer was too small
The same strategy is used in Rust for vector capacity allocation: https://github.com/rust-lang/rust/blob/0ca7f74dbd23a3e8ec491cd3438f490a3ac22741/src/liballoc/raw_vec.rs#L397
> more efficient buffer allocation

- src/ValueRepresentation.js
- test/data.test.js
When using this library with C-FIND requests via `dcmjs-dimse`, it is necessary to allow backslashes in UIDs because the spec says it is possible to query a list of UIDs by using a backslash as a delimiter.
Without this change UID list queries aren't possible in dcmjs-dimse because the backslashes get stripped out.
> Allow backslashes in UIDs in order to support C-FIND in dcmjs-dimse

- src/BufferStream.js
- src/ValueRepresentation.js
- test/data.test.js
Have run into a few bugs in the binary tag parsing on some DICOMs, and this PR contains fixes and test cases for those issues.
The two included DCM files are 13MB and 3MB - should these be hosted on GitHub releases like the other data is?
Details:
- Fix reading of OB tags with undefined length due to not handling trailing padding
- Fix reading of OB tags that use an offset table when there are large tags prior to the tag being read
- Make reading of sequence tags more explicit and add error checking
- Add two test cases for the above with DICOMs that previously had errors in parsing
> Fix errors parsing binary tags

- package.json
- src/BufferStream.js
- src/DicomDict.js
- src/DicomMessage.js
- src/Tag.js
- src/ValueRepresentation.js
- test/data-encoding.test.js
- test/data.test.js
- test/testUtils.js
refactored VR classes
refactored reading/writing ascii and encoded strings
changed hex writing to direct uint8 writing
reimplemented null padded read
removed unused code
unified test data loading and cache the test data locally for faster test runs
this fixes: https://github.com/dcmjs-org/dcmjs/issues/84
> added support for specific character set

- package-lock.json
- package.json
It is wrong to list "eslint-config-prettier" as runtime "dependency", it needs to be a "devDependency".
Having it as runtime dependencies introduces a large amount of licenses that the license checker will detect, which are not actually part of the deployed runtime of dcmjs.
> move "eslint-config-prettier" to devDependencies

- src/adapters/Cornerstone/MeasurementReport.js
- src/adapters/Cornerstone3D/MeasurementReport.js
For some reason (probably a force push) the imports for https://github.com/dcmjs-org/dcmjs/pull/274 was missing. I'm pretty sure I checked the PR and either was working for me or I fixed and pushed or not pushed. This is a fix for the missing import
> fix(imports): missing import for addAccessors

- src/DicomMessage.js
- test/data.test.js
- Fix several character sets not working, e.g. "ISO_IR 13" and "ISO_IR 166"
- Fix warning being shown when the "ISO_IR 6" character set is used
- Add tests for reading encoded string data in several different character sets
- Throw exception on an unsupported character set or multiple character sets rather than logging and continuing on (this can be overridden by setting ignoreErrors)
The new `encodingMapping` was based on code in `pydicom` as well as the DICOM spec.
> fix: several issues with character set handling

- src/utilities/orientation/nearlyEqual.js
Fix https://github.com/OHIF/Viewers/issues/2869, see https://github.com/OHIF/Viewers/issues/2869#issuecomment-1228331103 for more info
> fix: 🐛 relax condition in nearlyEquals check for detecting numbers near to zero

- src/sr/valueTypes.js
The value of the `MeasurementUnitsCodeSequence` attribute got incorrectly included into `NumContentItem`.
> Fix unit of sr num content item

- README.md
> feat(readme): stress need for a PR for npm package

- src/adapters/Cornerstone3D/ArrowAnnotate.js
- src/adapters/Cornerstone3D/Bidirectional.js
- src/adapters/Cornerstone3D/EllipticalROI.js
- src/adapters/Cornerstone3D/Length.js
- src/adapters/Cornerstone3D/PlanarFreehandROI.js
- src/adapters/Cornerstone3D/Probe.js
Cornerston3D's Annotation data type allows extending "data" field (key:value).
We are going to use the field to add "frameNumber" information to annotations.
This will help supporting multi-frame DICOM files on Cornerstone.
> Resolves #316 Cornerstone3D adaptor - Multiframe support - add "frameNumber" to the Annotation.data

- src/adapters/Cornerstone/FreehandRoi.js
Fix for issue #306. Missing tests but since dcmjs seems to be missing a testing setup for adapters I think someone more familiar with js testing and dcmjs should set the standard.
> Removed comment around getTID300RepresentationArguments 'tool' parameter

- src/adapters/Cornerstone3D/MeasurementReport.js
It's difficult to add all the SOPClassUIDs that supports multi-frames.
So it's unrealistic to rely on checking SOPClassUID for multi-frames.
Here the code is checking Instance's NumberOfFrames attribute (the instance is fetched from metadataProvider.).
Line 286 ~ 292 is the actual change, and other changes are just caused by prettier.
> fix: check instance's NumberOfFrames property to see if it is a multi-frame file or not

- src/utilities/TID300/index.js
This is to prepare dcmjs library to separate Cornerstone Adapter as a separate package.
https://github.com/dcmjs-org/dcmjs/pull/320#issuecomment-1275178945
In Cornerstone3D adapter code, the `utilities/TID300/Point` is being used, but this one is not publicly exported from dcmjs.
> Export TID300 - Point class

- README.md
Added a note in the README.md to add a space after the colon
> fix: Update the commit notes to include information about space after :

- README.md
Arg - @pieper - still wasn't quite right, it looks like it tests the first line of the overall commit message to master, NOT the individual commits, and that requires that the PR review name have the right message.  Hopefully this will be the last one!!!
> fix(semantic): Indicate that the review name needs the semantic

- src/DicomMetaDictionary.js
- src/ValueRepresentation.js
When naturalizing a dataset, the ValueRepresentation class used to add accessors may be ambiguous if the tag has multiple VR types. In this case we fall back to no accessor. There are only a handful of tags that fall into this category, and currently only PN has an accessor.
Specifically, this fixes the plethora of errors in OHIF stating `ValueRepresentation.js:262 Invalid vr type xs - using US`
> fix: 🐛 Check that VR has accessors for natural types (#368)

- src/adapters/Cornerstone/Segmentation_4X.js
- test/adapters.test.js
1. Issue overview
I am currently working on a project that automatically generates measurement report from mammography images.
It uses a DICOM web viewer based on OHIF to view its generated results. 
I noticed that the viewer throws an error when it loads the output of our application: mammography and segmentation images. The issue was caused by dcmjs module trying to parse some coordinate related tags from the source image of the SEG (i.e. MG image).
2. The cause
According to the standard, the segmentation IOD have 2 ways to describe its spatial relationship with the original images: one is using **Frame of Reference UID** along with coordinate system, and the other is having the segmentation pixel size identical to the original image and use **Derivation Image Functional  Group Macro** …
> fix: compatibility issue for SEG sourcing MG images

- .github/workflows/publish-package.yml
- package-lock.json
- package.json
- src/DicomDict.js
- src/Tag.js
- src/ValueRepresentation.js
- src/index.js
- test/SequenceOfItems.test.js
- test/adapters.test.js
Updated a number of versions, and started fixing the circular dependency issues to try to get the overall build/release working.
This does change the node version used to build, as well as the rollup version being used, but is intended to be entirely non-functional, just changing things trying to get the main build working.
@pieper  - this PR is just more than a basic test to try to release things again, so I'd like you to take a look before I push it.
> fix: Publish and build package on newer node

- .github/workflows/publish-package.yml
- .github/workflows/tests.yml
- README.md
- test/data-options.test.js
The change uses the URL that built correctly on the last deploy of dcmjs.  Looks like it should work this time.
> feat: Netlify app master-dcmjs2 deploy build

- src/DicomMessage.js
- src/ValueRepresentation.js
- src/utilities/deepEqual.js
- test/data.test.js
- test/lossless-read-write.test.js
- test/utilities/deepEqual.test.js
Solves https://github.com/dcmjs-org/dcmjs/issues/398 by implementing lossless round trip read/writes to preserve original file data when tags are unmodified
- Extracts any formatting or manipulation done to data element values into `ValueRepresentation.applyFormatting`
- Maintain reference to original value via new `_rawValue` property on a data element
- Detect changes to `Value` during writes to determine whether to maintain original unformatted value or update
- Filter `BinaryValueRepresentation` from lossless processing by default to avoid duplicating large arrayBuffers like pixel data, but provide override mechanism via `readOptions`
> feat(lossless-round-trip): Implement lossless read writes

- src/DicomMessage.js
- src/ValueRepresentation.js
- test/data.test.js
- test/lossless-read-write.test.js
Fixes issue during lossless read/write with numeric string value representations (`IS`/`DS`). This was caused by a string like:
`0.99924236548978\-0.0322633220972\-0.0217663285287\0.02949870928067\0.99267261121054\-0.1171789789306 ` where the space following the final number is correctly added for evenness, but produced an error during re-write as the unformatted value exceeded the max length of the VR.
Solution was to remove this padding byte from `_rawValue` property during read if it exceeds the max length of the vr. This padding will be re-added by the writer if needed for evenness.
> fix(lossles-round-trip): Account for padding byte in numeric strings with multiplicity

- src/DicomMetaDictionary.js
- test/data.test.js
Hello, I encountered several issues with saving the dataset to a file. 
After investigation I found that the source file has different vr that  in dictionary And the main problem is that after the `naturalizeDataset` process we lose origin vr for these tags and in the `denaturalizeDataset `process we try to process tag with incorrect vr 
and therefore we get the following errors when trying to write.
In dicom image (LUTData tag has incorrect vr. In standart it US)
We received that image and we get the following errors when trying to write
> feat(vr): Save original non-standard VR

- package.json
- src/DicomMessage.js
I have some data that fails to load in OHIF when draged and dropped ([try](https://viewer-dev.ohif.org/localbasic) ), and i have narrowed down the issue to an undefined value which this PR fixes
Here is the issue which has the data attached
https://github.com/OHIF/Viewers/issues/4588#issuecomment-2598032763
--
At OHIF, we use namify, and apparently, this data contains some undefined values that need to be addressed during the process.
> fix(dicomMessage): to handle undefined return value

- src/derivations/Segmentation.js
This pull request adds support for handling the optional DICOM SegmentDescription field during segment renumbering. If the source segment includes a SegmentDescription, it will be copied to the renumbered segment.
> Preserve optional DICOM SegmentDescription during renumbering

- README.md
Added link to [dcmjs-codecs](https://github.com/PantelisGeorgiadis/dcmjs-codecs) library which facilitates encapsulated dataset and part10 file transcoding among all major transfer syntaxes.
> Updated README to include dcmjs-codecs library

- src/DicomMetaDictionary.js
- src/ValueRepresentation.js
- test/data.test.js
This PR patches the work of @mishijima on #427.
More specifically,
- Removes the allowRangeMatching because the existence of rangeMatchingMaxLength, for a VR, gives the same information.
- Uses the existing checkLength function for DA, TM and DT to determine a range query and return whether the length is valid or not.
- Updates the unit tests to perform a full roundtrip between the naturalized and denaturalized worlds.
- The build output was used with dcmjs-dimse to make sure that range queries are working as expected.
@pieper please review and if you approve and merge, please close #427 since it is redundant.
> Using `checkLength` to determine max length for DA, DT, TM (Query with range matching)

- .github/workflows/publish-package.yml
- .github/workflows/tests.yml
Updated failing actions to utilize ubuntu-latest because github removed ubuntu-20.04 runner on 2025-04-15. This resulted in the failing execution of the `tests` and `publish-package` actions, and consequently prevented new PRs from being published.
> Updated failing github actions to use ubuntu-latest runner

- src/utilities/TID1500/TID1500MeasurementReport.js
- src/utilities/TID300/Bidirectional.js
- src/utilities/TID300/Calibration.js
- src/utilities/TID300/Circle.js
- src/utilities/TID300/CobbAngle.js
- src/utilities/TID300/Ellipse.js
- src/utilities/TID300/Length.js
- src/utilities/TID300/Point.js
- src/utilities/TID300/Polygon.js
- src/utilities/TID300/Polyline.js
- src/utilities/TID300/TID300Measurement.js
TID.300 measurements can now be defined using either 2D or 3D points. This is controlled by the use of either `SCOORD` (2D) or `SCOORD3D` (3D) in the **Measurement Value Sequence**, as described in the TID.320 section of TID.300:  
🔗 [DICOM TID.320 Reference](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_320)
TID.1501 defines the reference information for the SCOORD3D points:
🔗 [DICOM TID.1501 Reference](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_1501)
This pull request introduces support for selecting between `SCOORD` and `SCOORD3D` encodings in several TID.300 measurement types, including:
- Length  
- Bidirectional  
- Calibration  
- Cobb Angle  
- Ellipse  
This is achieved by allowing the …
> feat: Allow TID300 measurements to use either 2d or 3d points with SCOORD or SCOORD3D

- package.json
- rollup.config.mjs
- yarn.lock
For a project we want to use dcm.js in a browser context without build toolchain. Therefore, we would like to pull a minified version via a CDN.
This adds a minified version of the UMD build. It is ~1.10 MB vs ~1.65 MB for the original (33% reduction). 
Let me know if this looks right. I can also add a minified ESM build if that is preferred.
> feat(build): Create minified UMD build
