dcmjs-org/dcmjs

README.md
examples/createSegmentation/index.html
examples/displaySegmentation/index.html
examples/linearMeasurements/index.html
src/DicomMetaDictionary.js
src/datasetToBlob.js
src/derivations.js
src/normalizers.js

Stricter naming

---

.npmignore
package.json

Needed to have a working npm package.
@swederik, Can you build an republish?

Fix 'main' from package.json and add .npmignore.

---

examples/vtkDisplay/index.html

Should be similar to interaction in Slicer's 2D views, with scroll wheel slicing and window/level.

Port over image interactor style for volume-based slice viewing

---

src/DicomMessage.js

This adds a flag to readFile() to let the parser return partial results in the event of a read error due to a damaged file, for example a "RangeError: Offset is outside the bounds of the DataView" sort of thing. Should be analogous to dcmtk's dcmdump --ignore-errors flag.
Not sure if allowing more permissive parsing like this is attractive to others, feel free to discuss or suggest other solutions.

Add ignoreErrors flag to readFile() to allow partial read

---

src/adapters/DICOMMicroscopyViewer/MeasurementReport.js
src/adapters/DICOMMicroscopyViewer/Polyline.js

The ability to get the coordinates back from a dataset
With the coordinates, it will be possible to draw the selection back

Generate tool state microscopy viewer

---

examples/displaySegmentation/index.html
package.json
src/derivations/Segmentation.js

Branch working on creation of Segmentation objects with multiple segments.
TODO:
- Create adapter for cornerstone **DONE** (_in_ _JC's_ _voice_)
- Read adapter for cornerstone, with support for various in-plane orientations of the Segmentation object relative to the source data. **DONE** 
- Tidy up. **DONE**

WIP - Multi Segment Segmentations

---

package.json
src/derivations/Segmentation.js

Adds support for creating Segmentations that reference multiframe data in which the `PlaneOrientationSequence` is stored per frame.

Support for creating Segmentations on certain multiframe images.

---

src/DicomMessage.js
src/ValueRepresentation.js

Fixes #53
@emelalkim could you have a look at this PR and see if this will cause any problems on your end?  It should be backward compatible with anyone who called Number themselves.

bug(json) map number strings to be numbers

---

src/utilities/TID1500/TID1500MeasurementReport.js

Fix a bug introduced in 0.7.0.

Return the content item.

---

src/DicomMessage.js
src/ValueRepresentation.js
src/adapters/Cornerstone/MeasurementReport.js

1. Decimal String with multiplicity greater than 1 should be splitted as an array before transcode it as Number
2. We should filter tools that are not supported by Cornerstone adapter measurement report

Fix issues on v0.8.1

---

src/DicomMetaDictionary.js

fix: parsing of WADO-RS headers

---

src/DicomMetaDictionary.js
test/test_data.js

Revert "Avoid mutation in static DicomMetaDictionary methods"

---

src/DicomMetaDictionary.js
test/test_data.js

fix: Avoid mutation in static DicomMetaDictionary methods

---

.circleci/config.yml

Relates to: https://github.com/dcmjs-org/dcmjs/issues/100

CI support for runing tests on PR

---

src/index.js

fixes: https://github.com/dcmjs-org/dcmjs/issues/109

feat: add default export

---

src/adapters/Cornerstone/Segmentation_4X.js

Properly propogate errors so they can be caught by the hose application.
Feat. commented out super secret WIP code no one should look at, that'll be finished soon.

Out of plane error propagation for SEG.

---

examples/createSegmentation/index.html

feat: 🎸 Read/right findings in cornerstone SR

---

package.json
src/adapters/Cornerstone/Segmentation_4X.js
src/index.js
src/utilities/orientation/rotateDirectionCosinesInPlane.js
src/utilities/orientation/rotateVectorAroundUnitVector.js

RE: https://github.com/OHIF/Viewers/issues/2003
Fixes SEG mapping issues for the cornerstone segmentation adapter, when the data is rotated relative to the source data.

Fix rotation issues for different segs.

---

README.md
src/adapters/Cornerstone/Segmentation_4X.js

fix(idc-02252): typo + release

---

src/adapters/Cornerstone/Segmentation_4X.js

fix(Segmentation_4X): Update tag name in getSegmentIndex method for segs

---

src/sr/templates.js

- Allow text content item for qualitative evaluations, this will allow storage of freetext qualitative evaluations

Update sr qualitative evaluations conditional to allow text evaluations

---

src/adapters/Cornerstone/Segmentation_4X.js

IDC issue: https://github.com/OHIF/Viewers/issues/2345
Two main limitations are generated by the current cornerstone approach (segmentation geometry has to fit the one of the source images):
1) we can't have out of plane frames;
2) we can't have segmentation frames with different Columns and Rows attributes respect to the source frames.
in this PR we add checks to detect such data and abort the laoding.
Relevant IDC datasets:
- http://localhost:3000/projects/idc-dev-etl/locations/us-central1/datasets/idc/dicomStores/v2/study/1.3.6.1.4.1.14519.5.2.1.7311.5101.758555921127856064761732086690?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7311.5101.165636727522505811947315188478

fix: 🐛 ignore frames without SourceImageSequence information when loading a segmentation

---

src/adapters/Cornerstone/Segmentation_4X.js
src/utilities/orientation/index.js
src/utilities/orientation/nearlyEqual.js

Fix https://github.com/OHIF/Viewers/issues/2345#issuecomment-821910646 , @pieper @igoroctaviano could you please review and merge, please? thanks!

IDC2345: add tollerance parameter to generateToolState

---

src/adapters/Cornerstone/MeasurementReport.js

- Cut release (#201)
- Update jsdocs

fix(IDC-1215): update jsdocs, cut release

---

src/DicomMetaDictionary.js
test/mocks/minimal_fields_dataset.json
test/test_data.js

feature to support using a custom dictionary. Users can create an instance of the class DicomMetaDictionary and pass in their own dictionary on creation. They can then call the non-static function denaturalizeDataset to denaturalize the dataset.
#215

DicomMetaDictionary.js to accept custom dictionary

---

src/normalizers.js

MRImageFrameType -> MRImageFrameTypeSequence (0018,9226)

fix non existing named tag MRImageFrameType in MRImageNormalizer class

---

package-lock.json
src/adapters/Cornerstone/Segmentation_4X.js
src/utilities/orientation/nearlyEqual.js

Fix regression in https://github.com/OHIF/Viewers/issues/2003

fix: 🐛 IDC Re #2003: fix regression in parsing segmentation orietations

---

src/adapters/Cornerstone/Segmentation_4X.js

Separating the regression fix from https://github.com/dcmjs-org/dcmjs/pull/234

fix: 🐛 fix array format regression 

---

src/adapters/Cornerstone/Segmentation_4X.js

Improve find logic for segmentations reference source image Ids as discussed in https://github.com/OHIF/Viewers/issues/2733.
To find the refence source image id now we do:
1) we filter out source series with the segmentation ReferencedSeriesSequence.SeriesInstanceUID
2) we filter out source instances with the segmentation FrameOfReferenceUID
3) we filter out source instances with the segmentation PerFrameFunctionalGroup.PlanePositionSequence.ImagePositionPatient (within a tolerance)
If a source instance is not found for the segmentation frame, we do a last try using simply the segmentation frame ReferencedSOPInstanceUID

fix: 🐛 IDC2733: find segmentations reference source image Ids

---

src/adapters/Cornerstone/Segmentation_4X.js

Fix IDC https://github.com/OHIF/Viewers/issues/2761

fix: Re IDC #2761 fix loading of segmentations

---

.prettierrc
src/adapters/Cornerstone/Segmentation_4X.js
src/adapters/Cornerstone3D/Length.js
src/adapters/Cornerstone3D/MeasurementReport.js
src/adapters/Cornerstone3D/cornerstone3DTag.js
src/adapters/Cornerstone3D/index.js
src/adapters/index.js

- Adds the initial work for a Cornerstone3D adapter 
- Fixes the prettierrc which was missing
@JamesAPetts Can you review please

feat: Add Cornerstone3D adapter for Length tool

---

src/adapters/Cornerstone/CircleRoi.js
src/adapters/Cornerstone/index.js
src/utilities/TID300/Circle.js

Just add a circle adapter for cornerstone.

feat(dcmjs):Add Cornerstone circle adapter

---

src/adapters/Cornerstone/CircleRoi.js
src/utilities/TID300/Circle.js

The circle adapter was writing undefined for the area and diameter.

Fix the circle adapter to prevent writing undefined

---

package.json
src/utilities/TID1500/TID1500MeasurementReport.js

There was a typo, and saving when references only one series was broken.

Fix saving SR onto one series

---

test/data-options.test.js

I overlooked this test case when refactoring the test data loading.
This pull request adapst the test-options.test.js to also use the utility functions and cache the test data.

unified test data loading

---

src/ValueRepresentation.js
test/data.test.js

A padding byte for odd-length encapsulated binary data was being written at the end of writing the OB tag, but padding bytes need to be written for each frame, not the whole tag. That is, the last fragment for each frame should get a padding byte if that frame's data is of uneven length. This is also the behaviour of pydicom.
Closes #293.

fix(fragment): write padding to even length on final fragments of encapsulated frame data

---

src/BufferStream.js
test/data.test.js

Fixes #324 and adds a test covering these values

fix: exception writing NaN and Infinity values of FD tags

---

src/adapters/Cornerstone/Segmentation_4X.js

Fixes https://github.com/OHIF/Viewers/issues/3047
https://user-images.githubusercontent.com/112136540/208823474-4dc5eb52-81f0-4988-ad38-c43c8c1f5da8.mp4

fix: update variable name for frame index

---

src/utilities/index.js

There are some additional classes needed to externalize the adapters.  No functional change.

fix:Add more utilities - compression, addAccessor, orientation

---

src/utilities/TID300/index.js

export Circle and Polygon in TID300

fix(exports): export Circle and Polygon in TID300

---

package-lock.json

Updating @babel/traverse package to fix critical security issue.
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
node_modules/@babel/traverse

fix: critical security issue

---

README.md

Adjust the deploy preview to be dcmjs2 - have to see if this will autodeploy on merge now.

fix(examples):Fix deployment of examples

---

generate-dictionary.js
src/dictionary.js

- Fixes issue running generate-dictionary script
- Update source dictionary to latest version of the DICOM spec

fix(generate-dictionary): update generate script to use https and regenerate source dictionary

---

package.json
yarn.lock

- https://github.com/dcmjs-org/dcmjs/security/dependabot/47
- https://github.com/dcmjs-org/dcmjs/security/dependabot/46

fix(yarn.lock): address high and critical vulnerabilities

---

jest.setup.js
package.json
rollup.config.mjs
src/log.js
test/anonymizer.test.js
test/data.test.js
test/integration/DicomMessage.readFile.test.js
test/testUtils.js
yarn.lock

- Address runtime errors
- Address https://github.com/dcmjs-org/dcmjs/issues/411

fix(log): Add process env to rollup and update api

---

test/data.test.js

Add a test for labelmap segmentation

feat(seg): add labelmap seg test

---

src/sr/contentItems.js
src/sr/templates.js
src/sr/valueTypes.js

- https://github.com/ImagingDataCommons/slim/issues/304

fix: Use instanceof instead of constructor checks for content item, templates and value types
